###########################################
# CONDUCTORES
###########################################

# Obtener todos los conductores
GET http://127.0.0.1:8000/conductor/
Accept: application/json

###

# Obtener un conductor por ID
GET http://127.0.0.1:8000/conductor/8
Accept: application/json

###

# Crear un conductor
POST http://127.0.0.1:8000/conductor/
Content-Type: application/json

{
  "nombre": "Alejandro",
  "genero": "Masculino",
  "dni": "12345670A",
  "telefono": 123456720
}

###

# Actualizar un conductor
PUT http://127.0.0.1:8000/conductor/1
Content-Type: application/json

{
  "nombre": "Nacho Martin",
  "genero": "Masculino",
  "dni": "12345678A",
  "telefono": "987654321"
}

###

# Eliminar un conductor
DELETE http://127.0.0.1:8000/conductor/1

###########################################
# COCHES
###########################################

# Obtener todos los coches
GET http://127.0.0.1:8000/coche/
Accept: application/json

###

# Obtener un coche por ID
GET http://127.0.0.1:8000/coche/1
Accept: application/json

###

# Crear un coche
POST http://127.0.0.1:8000/coche/
Content-Type: application/json

{
  "nombre": "MiCoche",
  "marca": "Toyota",
  "matricula": "Gasolina",
  "age": 3,
  "conductor_id": 2
}

###

# Actualizar un coche
PUT http://127.0.0.1:8000/coche/1
Content-Type: application/json

{
  "nombre": "MiCocheActualizado",
  "marca": "Toyota",
  "matricula": "Gasolina",
  "age": 3,
  "conductor_id": 1
}

###

# Eliminar un coche
DELETE http://127.0.0.1:8000/coche/1
